package id.co.asyst.bukopin.mobile.user.core.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import id.co.asyst.bukopin.mobile.user.model.soap.cif.Fault;
import id.co.asyst.bukopin.mobile.user.model.soap.cif.GetInquiryCIFReqType;
import id.co.asyst.bukopin.mobile.user.model.soap.cif.GetInquiryCIFResType;
import id.co.asyst.bukopin.mobile.user.model.soap.cif.HeaderRQ;
import id.co.asyst.bukopin.mobile.user.model.soap.cif.HeaderRS;
import id.co.asyst.bukopin.mobile.user.model.soap.cif.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-10-27T21:13:22.066+07:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://xmlns.example.com/1563943224814", name = "GetInquiryCIFPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetInquiryCIFPortType {

    @WebMethod(operationName = "GetInquiryCIF", action = "GetInquiryCIF")
    public void getInquiryCIF(

        @WebParam(partName = "HeaderRQ", name = "HeaderRQ", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true)
        HeaderRQ headerRQ,
        @WebParam(partName = "InquiryCIFRQ", name = "GetInquiryCIFReq", targetNamespace = "http://xml.asyst.co.id/cbs/listing/cif/getinquirycif/v1_0")
        GetInquiryCIFReqType inquiryCIFRQ,
        @WebParam(partName = "HeaderRS", mode = WebParam.Mode.OUT, name = "HeaderRS", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true)
        javax.xml.ws.Holder<HeaderRS> headerRS,
        @WebParam(partName = "InquiryCIFRS", mode = WebParam.Mode.OUT, name = "GetInquiryCIFRes", targetNamespace = "http://xml.asyst.co.id/cbs/listing/cif/getinquirycif/v1_0")
        javax.xml.ws.Holder<GetInquiryCIFResType> inquiryCIFRS
    ) throws Fault;
}
