package id.co.asyst.bukopin.mobile.user.core.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import id.co.asyst.bukopin.mobile.user.model.soap.account.Fault;
import id.co.asyst.bukopin.mobile.user.model.soap.account.GetAccountBalanceReqType;
import id.co.asyst.bukopin.mobile.user.model.soap.account.GetAccountBalanceResType;
import id.co.asyst.bukopin.mobile.user.model.soap.account.GetInquiryTransactionReqType;
import id.co.asyst.bukopin.mobile.user.model.soap.account.GetInquiryTransactionResType;
import id.co.asyst.bukopin.mobile.user.model.soap.account.HeaderRQ;
import id.co.asyst.bukopin.mobile.user.model.soap.account.HeaderRS;
import id.co.asyst.bukopin.mobile.user.model.soap.account.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-10-27T21:13:21.898+07:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://xmlns.example.com/1535711330238", name = "PortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PortType {

    @WebMethod(operationName = "GetInquiryTransaction", action = "http://ws.bukopin.co.id/cbs/listing/accountstatement/inquirytransaction")
    public void getInquiryTransaction(

        @WebParam(partName = "HeaderRQ", name = "HeaderRQ", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true)
        HeaderRQ headerRQ,
        @WebParam(partName = "GetInquiryTransactionRQ", name = "GetInquiryTransactionReq", targetNamespace = "http://xml.asyst.co.id/cbs/listing/statement/getinquirytransaction/v1_0")
        GetInquiryTransactionReqType getInquiryTransactionRQ,
        @WebParam(partName = "HeaderRS", mode = WebParam.Mode.OUT, name = "HeaderRS", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true)
        javax.xml.ws.Holder<HeaderRS> headerRS,
        @WebParam(partName = "GetInquiryTransactionRS", mode = WebParam.Mode.OUT, name = "GetInquiryTransactionRes", targetNamespace = "http://xml.asyst.co.id/cbs/listing/statement/getinquirytransaction/v1_0")
        javax.xml.ws.Holder<GetInquiryTransactionResType> getInquiryTransactionRS
    ) throws Fault;

    @WebMethod(operationName = "GetAccountBalance", action = "http://ws.bukopin.co.id/cbs/listing/accountstatement/accountbalance")
    public void getAccountBalance(

        @WebParam(partName = "HeaderRQ", name = "HeaderRQ", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true)
        HeaderRQ headerRQ,
        @WebParam(partName = "GetAccountBalanceRQ", name = "GetAccountBalanceReq", targetNamespace = "http://xml.asyst.co.id/cbs/listing/statement/getaccountbalance/v1_0")
        GetAccountBalanceReqType getAccountBalanceRQ,
        @WebParam(partName = "HeaderRS", mode = WebParam.Mode.OUT, name = "HeaderRS", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true)
        javax.xml.ws.Holder<HeaderRS> headerRS,
        @WebParam(partName = "GetAccountBalanceRS", mode = WebParam.Mode.OUT, name = "GetAccountBalanceRes", targetNamespace = "http://xml.asyst.co.id/cbs/listing/statement/getaccountbalance/v1_0")
        javax.xml.ws.Holder<GetAccountBalanceResType> getAccountBalanceRS
    ) throws Fault;
}
