package id.co.asyst.bukopin.mobile.user.core.service.soap;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-10-27T21:13:22.072+07:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "Service-InquiryCIF",
                  wsdlLocation = "classpath:wsdl/InquiryCIFWS-concrete.wsdl",
                  targetNamespace = "http://xmlns.example.com/1563943224814")
@org.springframework.stereotype.Service
@HandlerChain(file="handler-chain.xml")
public class ServiceInquiryCIF extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.example.com/1563943224814", "Service-InquiryCIF");
    public final static QName GetInquiryCIFPortTypeEndpoint1 = new QName("http://xmlns.example.com/1563943224814", "GetInquiryCIFPortTypeEndpoint1");
    static {
        URL url = null;
        try {
            url = new URL("classpath:wsdl/InquiryCIFWS-concrete.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceInquiryCIF.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/InquiryCIFWS-concrete.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceInquiryCIF(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceInquiryCIF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceInquiryCIF() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiceInquiryCIF(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiceInquiryCIF(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiceInquiryCIF(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GetInquiryCIFPortType
     */
    @WebEndpoint(name = "GetInquiryCIFPortTypeEndpoint1")
    public GetInquiryCIFPortType getGetInquiryCIFPortTypeEndpoint1() {
        return super.getPort(GetInquiryCIFPortTypeEndpoint1, GetInquiryCIFPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetInquiryCIFPortType
     */
    @WebEndpoint(name = "GetInquiryCIFPortTypeEndpoint1")
    public GetInquiryCIFPortType getGetInquiryCIFPortTypeEndpoint1(WebServiceFeature... features) {
        return super.getPort(GetInquiryCIFPortTypeEndpoint1, GetInquiryCIFPortType.class, features);
    }

}
