
package id.co.asyst.bukopin.mobile.user.core.service.soap;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;

import id.co.asyst.bukopin.mobile.user.model.soap.statement.Fault;
import id.co.asyst.bukopin.mobile.user.model.soap.statement.GetMiniStatementReqType;
import id.co.asyst.bukopin.mobile.user.model.soap.statement.GetMiniStatementResType;
import id.co.asyst.bukopin.mobile.user.model.soap.statement.GetStatementByDateRangeReqType;
import id.co.asyst.bukopin.mobile.user.model.soap.statement.GetStatementByDateRangeResType;
import id.co.asyst.bukopin.mobile.user.model.soap.statement.HeaderRQ;
import id.co.asyst.bukopin.mobile.user.model.soap.statement.HeaderRS;
import id.co.asyst.bukopin.mobile.user.model.soap.statement.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatementPT", targetNamespace = "http://xmlns.example.com/1535727132417")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StatementPT {


    /**
     * 
     * @param headerRS
     * @param getMiniStatementRS
     * @param headerRQ
     * @param getMiniStatementRQ
     * @throws Fault
     */
    @WebMethod(operationName = "GetMiniStatement", action = "http://ws.bukopin.co.id/cbs/listing/statement/getministatement")
    public void getMiniStatement(
        @WebParam(name = "HeaderRQ", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, partName = "headerRQ")
        HeaderRQ headerRQ,
        @WebParam(name = "GetMiniStatementReq", targetNamespace = "http://xml.asyst.co.id/cbs/listing/statement/getministatement/v1_0", partName = "GetMiniStatementRQ")
        GetMiniStatementReqType getMiniStatementRQ,
        @WebParam(name = "HeaderRS", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, mode = WebParam.Mode.OUT, partName = "headerRS")
        Holder<HeaderRS> headerRS,
        @WebParam(name = "GetMiniStatementRes", targetNamespace = "http://xml.asyst.co.id/cbs/listing/statement/getministatement/v1_0", mode = WebParam.Mode.OUT, partName = "GetMiniStatementRS")
        Holder<GetMiniStatementResType> getMiniStatementRS)
        throws Fault
    ;

    /**
     * 
     * @param statementRS
     * @param headerRS
     * @param headerRQ
     * @param statementRQ
     * @throws Fault
     */
    @WebMethod(operationName = "GetStatementByDateRange", action = "http://ws.bukopin.co.id/cbs/listing/statement/getstatementbydate")
    public void getStatementByDateRange(
        @WebParam(name = "HeaderRQ", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, partName = "headerRQ")
        HeaderRQ headerRQ,
        @WebParam(name = "GetStatementByDateRangeReq", targetNamespace = "http://xml.asyst.co.id/cbs/listing/statement/getstatementbydaterange/v1_0", partName = "statementRQ")
        GetStatementByDateRangeReqType statementRQ,
        @WebParam(name = "HeaderRS", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, mode = WebParam.Mode.OUT, partName = "headerRS")
        Holder<HeaderRS> headerRS,
        @WebParam(name = "GetStatementByDateRangeRes", targetNamespace = "http://xml.asyst.co.id/cbs/listing/statement/getstatementbydaterange/v1_0", mode = WebParam.Mode.OUT, partName = "statementRS")
        Holder<GetStatementByDateRangeResType> statementRS)
        throws Fault
    ;

}
