#################################################
# DEVELOPMENT Server Profile - Transfer         #
#################################################

## Application configurations:
server:
   port: 8081
   servlet:
      context-path: /bukopinmobile-transfer


## Database configuration:
#spring.jpa.hibernate.ddl-auto=create
spring:
   datasource:
      #url: jdbc:postgresql://10.2.62.224:5432/DB_MBANKING
      url: jdbc:postgresql://10.2.62.231:5432/DB_MBANKING 
      username: postgres
      password: bukopin
      driver-class-name: org.postgresql.Driver
      maxActive: 10
   jpa:
      hibernate:
         #ddl-auto: update
         ddl-auto: none      
         #spring.jpa.hibernate.ddl-auto=none
      properties:
         hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
         hibernate.jdbc.lob.non_contextual_creation: true

## LIQUIBASE (LiquibaseProperties)
# spring.liquibase.enabled=false

## LOGGING
logging:
   level:
      root: ERROR
      id.co.asyst: TRACE

jwt:
   header: Authorization
   
## CONFIG
config:
   max:
      most.frequent: 3 # maximum size of most frequent list result 
      receiver:
         overbook: 25 # maximum size of favourite overbook list result
         transfer: 25 # maximum size of favourite transfer list result

## IP CONFIG
   ip:
      passtrough: # client ip no need token
         10.2.62.163, 
         0.0.0.1,
         0:0:0:0:0:0:0:1
            
## url for other module
url:
   masterdata:
      configuration: http://10.2.62.163:8082/
   user: http://10.2.62.163:8080/