
package id.co.asyst.bukopin.mobile.master.core.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.Fault;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.HeaderRQ;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.HeaderRS;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.ObjectFactory;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.Reqexchangerate;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.Resexchangerate;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(targetNamespace = "http://xmlns.example.com/1571040722628", name = "ExchangeRatePT")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})

public interface ExchangeRatePT {


    /**
     * 
     * @param headerRS
     * @param exchangeRateRQ
     * @param headerRQ
     * @param exchangeRateRS
     * @throws Fault
     */
    @WebMethod(operationName = "GetExchangeRate", action = "http://ws.bukopin.co.id/cbs/exchangerate/exchangeratetransaction")
    public void getExchangeRate(
        @WebParam(name = "HeaderRQ", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, partName = "headerRQ")
        HeaderRQ headerRQ,
        @WebParam(name = "reqexchangerate", targetNamespace = "http://xml.asyst.co.id/cbs/exchangerate", partName = "exchangeRateRQ")
        Reqexchangerate exchangeRateRQ,
        @WebParam(name = "HeaderRS", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, mode = WebParam.Mode.OUT, partName = "headerRS")
        javax.xml.ws.Holder<HeaderRS> headerRS,
        @WebParam(name = "resexchangerate", targetNamespace = "http://xml.asyst.co.id/cbs/exchangerate", mode = WebParam.Mode.OUT, partName = "exchangeRateRS")
        javax.xml.ws.Holder<Resexchangerate> exchangeRateRS)
        throws Fault
    ;

}
