
package id.co.asyst.bukopin.mobile.master.core.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.Fault;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.HeaderRQ;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.HeaderRS;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.ObjectFactory;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.Reqproductinformation;
import id.co.asyst.bukopin.mobile.master.model.soap.exchange.rate.Resproductinformation;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductInfoPT", targetNamespace = "http://xmlns.example.com/1571383336914")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductInfoPT {


    /**
     * 
     * @param headerRS
     * @param productInfoRS
     * @param headerRQ
     * @param productInfoRQ
     * @throws Fault
     */
    @WebMethod(operationName = "GetProductInfo", action = "http://ws.bukopin.co.id/cbs/productinfo/getproductinfo")
    public void getProductInfo(
        @WebParam(name = "HeaderRQ", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, partName = "headerRQ")
        HeaderRQ headerRQ,
        @WebParam(name = "reqproductinformation", targetNamespace = "http://xml.asyst.co.id/cbs/product/productinformation", partName = "productInfoRQ")
        Reqproductinformation productInfoRQ,
        @WebParam(name = "HeaderRS", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, mode = WebParam.Mode.OUT, partName = "headerRS")
        javax.xml.ws.Holder<HeaderRS> headerRS,
        @WebParam(name = "resproductinformation", targetNamespace = "http://xml.asyst.co.id/cbs/product/productinformation", mode = WebParam.Mode.OUT, partName = "productInfoRS")
        javax.xml.ws.Holder<Resproductinformation> productInfoRS
        ) throws Fault;

}
