#################################################
# DEFAULT (localhost) Profile                   #
#################################################

## Application configurations:
server:
   port: 8083
   servlet:
      context-path: /bukopinmobile-purchase


## Database configuration:
#spring.jpa.hibernate.ddl-auto=create
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/bkpm_user_local
      username: apps
      password: Apps*2013
      driver-class-name: com.mysql.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update      
         #spring.jpa.hibernate.ddl-auto=none
      properties:
         hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
         hibernate.jdbc.lob.non_contextual_creation: true
   mail:
      host: 10.0.14.23
      port: 25
      username: noreply_mobile@bukopin.co.id
      password: 
      properties:
         mail:
            smtp:
               auth: true
               connectiontimeout: 5000
               timeout: 5000
               writeout: 5000
               starttls:
                  enable: true

## LIQUIBASE (LiquibaseProperties)
# spring.liquibase.enabled=false

## LOGGING
#logging:
 #  level:
  #    root: ERROR
   #   id.co.asyst: TRACE
logging:
   level:
      id.co.asyst: TRACE
      org:
         springframework:
            web: DEBUG
         ws:
            client:
               MessageTracing:
                  sent: DEBUG
                  received: TRACE
            server:
               MessageTracing:
                  sent: DEBUG
                  received: TRACE

config:
   emoney:
      forwarding-institution-code: 4411338
   ## IP CONFIG
   ip:
      passtrough: # client ip no need token
         10.2.62.163,
         10.2.62.164, 
         0:0:0:0:0:0:0:1,
         127.0.0.1
