#################################################
# TEST Server Profile                           #
#################################################

## Application configurations:
server:
   port: 8080


## Database configuration:
#spring.jpa.hibernate.ddl-auto=create
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/wfm_opt_local
      username: apps
      password: Apps*2013
      driver-class-name: com.mysql.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: none      
         #spring.jpa.hibernate.ddl-auto=none
      properties:
         hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
