
package id.co.asyst.bukopin.mobile.transfer.core.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import id.co.asyst.bukopin.mobile.transfer.model.soap.posting.Posting;
import id.co.asyst.bukopin.mobile.transfer.model.soap.posting.Fault;
import id.co.asyst.bukopin.mobile.transfer.model.soap.posting.HeaderRQ;
import id.co.asyst.bukopin.mobile.transfer.model.soap.posting.HeaderRS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PostingPT", targetNamespace = "http://wsdl.bukopin.co.id/cbs/posting")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    id.co.asyst.bukopin.mobile.transfer.model.soap.posting.ObjectFactory.class
})
public interface PostingPT {


    /**
     * 
     * @param headerReq
     * @param headerRes
     * @param postingRes
     * @param postingReq
     * @throws Fault
     */
    @WebMethod(operationName = "PostTransaction", action = "http://ws.bukopin.co.id/cbs/posting/posttransaction")
    public void postTransaction(
        @WebParam(name = "HeaderRQ", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, partName = "headerReq")
        HeaderRQ headerReq,
        @WebParam(name = "Posting", targetNamespace = "http://xml.asyst.co.id/cbs/posting/proxy", partName = "postingReq")
        Posting postingReq,
        @WebParam(name = "HeaderRS", targetNamespace = "http://xml.asyst.co.id/commons/ws/header", header = true, mode = WebParam.Mode.OUT, partName = "headerRes")
        Holder<HeaderRS> headerRes,
        @WebParam(name = "Posting", targetNamespace = "http://xml.asyst.co.id/cbs/posting/proxy", mode = WebParam.Mode.OUT, partName = "postingRes")
        Holder<Posting> postingRes)
        throws Fault
    ;

}
