#################################################
# DEFAULT (localhost) Profile                   #
#################################################

## Application configurations:
server:
   port: 8081
   servlet:
      context-path: /bukopinmobile-transfer


## Database configuration:
#spring.jpa.hibernate.ddl-auto=create
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/bkpm_user_local
      username: apps
      password: Apps*2013
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 10
      initialization-mode: never # always (on) or never (off)
   jpa:
      hibernate:
         ddl-auto: update      
         #spring.jpa.hibernate.ddl-auto=none
         naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
         hibernate.jdbc.lob.non_contextual_creation: true
   mail:
      host: 10.2.62.224
      port: 8587
      username: noreply_mobile@bukopin.co.id
      password: Bukopin@2019
      properties:
         mail:
            smtp:
               auth: true
               connectiontimeout: 5000
               timeout: 5000
               writeout: 5000
               starttls:
                  enable: true
      
## LIQUIBASE (LiquibaseProperties)
#spring.
   liquibase:
      enabled: false

## LOGGING
logging:
   level:
      root: ERROR
      id.co.asyst: TRACE

jwt:
   header: Authorization
   
## CONFIG
config:
   max:
      most.frequent: 3 # maximum size of most frequent list result 
      receiver:
         overbook: 25 # maximum size of favourite overbook list result
         transfer: 25 # maximum size of favourite transfer list resul

## IP CONFIG
   ip:
      passtrough: # client ip no need token
         10.2.62.163,
         0.0.0.1,
         0:0:0:0:0:0:0:1
   
## url for other module
url:
   masterdata:
      configuration: http://localhost:8082/
   user: http://10.2.62.163:8080/
