#################################################
# DEVELOPMENT Server Profile - Transfer         #
#################################################

## Application configurations:
server:
   port: 8081
   servlet:
      context-path: /bukopinmobile-transfer


## Database configuration:
spring:
   datasource:
      url: jdbc:sqlserver://10.0.24.83:1433;databaseName=DB_MBANKING 
      username: dbapp
      password: 'Bukopin20@$*#'
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      maxActive: 10
      initialization-mode: never # always (on) or never (off)
   jpa:
      hibernate:
         ddl-auto: update # update, create, none
         naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate.dialect: org.hibernate.dialect.SQLServerDialect
   mail:
      host: smtp.office365.com
      port: 587
      username: noreply_mobile@bukopin.co.id
      password: Bukopin@2019
      properties:
         mail:
            smtp:
               auth: true
               connectiontimeout: 5000
               timeout: 5000
               writeout: 5000
               starttls:
                  enable: true

## LIQUIBASE (LiquibaseProperties)
# spring.liquibase.enabled=false

## LOGGING
logging:
   level:
      root: ERROR
      id.co.asyst: TRACE

jwt:
   header: Authorization
   
## CONFIG
config:
   max:
      most.frequent: 3 # maximum size of most frequent list result 
      receiver:
         overbook: 25 # maximum size of favourite overbook list result
         transfer: 25 # maximum size of favourite transfer list result

## IP CONFIG
   ip:
      passtrough: # client ip no need token
         10.0.13.61,
         10.0.13.51,
         10.0.13.52,
         10.0.13.53,
         10.0.13.54, 
         0:0:0:0:0:0:0:1,
         127.0.0.1
   header:
      overbook:
         api-key: 77474043-b7a0-489f-81c5-387ae027f8aa
            
## url for other module
url:
   masterdata:
      configuration: http://10.0.13.54:8082/
   user: http://10.0.13.54:8080/