#################################################
# DEVELOPMENT Server Profile                    #
#################################################

## Application configurations:
server:
   port: 8085
   servlet:
      context-path: /bukopinmobile-telco


## Database configuration:
spring:
   datasource:
      url: jdbc:sqlserver://10.0.24.83:1433;databaseName=DB_MBANKING 
      username: dbapp
      password: 'Bukopin20@$*#'
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      maxActive: 10
      initialization-mode: never # always (on) or never (off)
   jpa:
      hibernate:
         ddl-auto: update # update, create, none
         naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate.dialect: org.hibernate.dialect.SQLServerDialect
   mail:
      host: smtp.office365.com
      port: 587
      username: noreply_mobile@bukopin.co.id
      password: Bukopin@2019
      properties:
         mail:
            smtp:
               auth: true
               connectiontimeout: 60000
               timeout: 60000
               writeout: 60000
               starttls:
                  enable: true

## LIQUIBASE (LiquibaseProperties)
# spring.liquibase.enabled=false

## LOGGING
logging:
   level:
      root: ERROR
      id.co.asyst: TRACE
               
## url for other module
url:
   masterdata:
      configuration: http://10.0.13.54:8082/
   user: http://10.0.13.54:8080/
   
config:
   forwarding-institution-code: 4390003
   ## IP CONFIG
   ip:
      passtrough: # client ip no need token
         10.0.13.61,
         10.0.13.51,
         10.0.13.52,
         10.0.13.53,
         0:0:0:0:0:0:0:1,
         127.0.0.1
   status:
      redis: 0 #1 is active, 0 is disable
      
