#################################################
# DOCKER (localhost) Profile                    #
#################################################

## Application configurations:
server:
   port: 8080


## Database configuration:
spring:
   datasource:
      url: jdbc:mysql://host.docker.internal:3306/bkpm_telco_local
   jpa:
      hibernate:
         ddl-auto: update      
