#################################################
# DEFAULT (localhost) Profile                   #
#################################################

## Application configurations:
server:
   port: 8080
   servlet:
      context-path: /bukopinmobile-user


## Database configuration:
#spring.jpa.hibernate.ddl-auto=create
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/bkpm_user_local
      username: apps
      password: Apps*2013
      driver-class-name: com.mysql.jdbc.Driver
      initialization-mode: never # always (on) or never (off)
   jpa:
      hibernate:
         ddl-auto: update      
         #spring.jpa.hibernate.ddl-auto=none
      properties:
         hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
         hibernate.jdbc.lob.non_contextual_creation: true
   mail:
      host: 10.0.14.23
      port: 25
      username: noreply_mobile@bukopin.co.id
      password:
      properties:
         mail:
            smtp:
               auth: true
               connectiontimeout: 5000
               timeout: 5000
               writeout: 5000
               starttls:
                  enable: true

## BUKOPIN INTERNAL DATABASE
bukopin:
   datasource:
      url: jdbc:sqlserver://10.2.62.231:1433;databaseName=XlinkDWH
      username: sa
      password: Bukopin@)!%
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      #url: jdbc:mysql://localhost:3306/bkpm_internal
      #username: apps
      #password: Apps*2013
      #driver-class-name: com.mysql.jdbc.Driver
   hibernate:
      #ddl-auto: none
      dialect: org.hibernate.dialect.SQLServerDialect

## LIQUIBASE (LiquibaseProperties)
# spring.liquibase.enabled=false

## LOGGING
#logging:
 #  level:
  #    root: ERROR
   #   id.co.asyst: TRACE
      #javax.xml.ws: TRACE
logging:
   level:
      id.co.asyst: TRACE
      org:
         springframework:
            web: DEBUG
         ws:
            client:
               MessageTracing:
                  sent: DEBUG
                  received: TRACE
            server:
               MessageTracing:
                  sent: DEBUG
                  received: TRACE

jwt:
   header: Authorization
   
## SOAP URL
soap:
   url:
      country: http://localhost:8080/ws
      
      
## CENTAGATE CONFIG
centagate:
   algorithm:
      hmac: HmacSHA256
   user:
      admin: anabaticadmin
      test: wowo@gmail.com
   password:
      admin: ana123
      test: Bukopin123
   key:
      secret: mKYGKb2PBeza
      integration: 2918332a0f44b24cd8f43b5a7ec6cdae53b9f314a1b8ce30ed55612b1c3baee3


## IP CONFIG
config:
   ip:
      passtrough: # client ip no need token
         10.2.62.163, 
         0.0.0.1.
         0:0:0:0:0:0:0:1

         
## url for other module
url:
   masterdata:
      configuration: http://localhost:8082/
   user: http://10.2.62.163:8080/