#################################################
# DEFAULT (localhost) Profile                   #
#################################################

## Application configurations:
server:
   port: 8080
   servlet:
      context-path: /bukopinmobile-user


## Database configuration:
#spring.jpa.hibernate.ddl-auto=create
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/bkpm_user_local
      username: apps
      password: Apps*2013
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 10
      initialization-mode: never # always (on) or never (off)
   jpa:
      hibernate:
         ddl-auto: update      
         #spring.jpa.hibernate.ddl-auto=none
         naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
         hibernate.jdbc.lob.non_contextual_creation: true
   mail:
      host: 10.2.62.224
      port: 8587
      username: noreply_mobile@bukopin.co.id
      password: Bukopin@2019
      properties:
         mail:
            smtp:
               auth: true
               connectiontimeout: 5000
               timeout: 5000
               writeout: 5000
               starttls:
                  enable: true

## BUKOPIN INTERNAL DATABASE
bukopin:
   datasource:
      url: jdbc:mysql://localhost:3306/bkpm_internal 
      username: apps 
      password: Apps*2013 
      driver-class-name: com.mysql.jdbc.Driver
   hibernate:
      #ddl-auto: none,
      dialect: org.hibernate.dialect.SQLServerDialect

## LIQUIBASE (LiquibaseProperties)
# spring.liquibase.enabled=false

## LOGGING
logging:
   level:
      root: ERROR
      id.co.asyst: TRACE

jwt:
   header: Authorization
   
## SOAP URL
soap:
   url:
      country: http://localhost:8080/ws
      
      
## CENTAGATE CONFIG
centagate:
   algorithm:
      hmac: HmacSHA256
   user:
      admin: bmobile-dev
      test: wowo@gmail.com
   password:
      admin: BkpM2019
      test: Bukopin123
   key:
      secret: lZ6zlyU110Z9
      integration: 41964610fc416180c678735ac073009ead25b8c55d4c6b0d40d9f6f506eaa14d

## IP CONFIG
config:
   ip:
      passtrough: # client ip no need token
         10.2.62.163,
         10.2.62.164,
         10.2.62.222, 
         0:0:0:0:0:0:0:1,
         127.0.0.1

         
## url for other module
url:
   masterdata:
      configuration: http://localhost:8082/
   user: http://10.2.62.163:8080/