
package id.co.asyst.bukopin.mobile.user.model.soap.statement;

import javax.xml.ws.WebFault;
import id.co.asyst.bukopin.mobile.user.model.soap.statement.ErrList;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ErrList", targetNamespace = "http://xml.asyst.co.id/commons/ws/fault")
public class Fault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrList faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Fault(String message, ErrList faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Fault(String message, ErrList faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: id.co.asyst.xml.commons.ws.fault.ErrList
     */
    public ErrList getFaultInfo() {
        return faultInfo;
    }

}
