#################################################
# DEVELOPMENT Server Profile                    #
#################################################

## Application configurations:
server:
   port: 8082
   servlet:
      context-path: /bukopinmobile-master


## Database configuration:
#spring.jpa.hibernate.ddl-auto=create
spring:
   application:
      name: bkpm-master
   datasource:
      url: jdbc:sqlserver://10.2.62.51:1433;databaseName=DB_MBANKING 
      username: sa
      password: Bukopin@2020
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      maxActive: 10
      initialization-mode: never # always (on) or never (off)
   jpa:
      hibernate:
         ddl-auto: update # update, create, none
         naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
         #spring.jpa.hibernate.ddl-auto=none
      properties:
         hibernate.dialect: org.hibernate.dialect.SQLServerDialect
         #hibernate.jdbc.lob.non_contextual_creation: true

## ELASTIC
   data:
      elasticsearch:
         cluster-name: elasticsearch
         cluster-nodes: 10.2.62.119:9200
         username: elastic
         password: Bukopin2020
         ##cluster-nodes: localhost:9200
         
## LIQUIBASE (LiquibaseProperties)
# spring.liquibase.enabled=false

## LOGGING
#logging:
#   file: /home/dev/BKPM-LOGS/master/master.log

jwt:
   header: Authorization

config:
   status:
      redis: 0 #1 is active, 0 is disable
    ## IP CONFIG
   ip:
      passtrough: # client ip no need token
         10.2.62.163,
         10.2.62.164,
         10.2.62.222,
         0:0:0:0:0:0:0:1,
         127.0.0.1