
package id.co.asyst.bukopin.mobile.transfer.core.service.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CBSPostingHTTP", targetNamespace = "http://wsdl.bukopin.co.id/cbs/posting", 
wsdlLocation = "classpath:wsdl/CBSPostingHttp.wsdl")
@org.springframework.stereotype.Service
public class CBSPostingHTTP
    extends Service
{

    private final static URL CBSPOSTINGHTTP_WSDL_LOCATION;
    private final static WebServiceException CBSPOSTINGHTTP_EXCEPTION;
    private final static QName CBSPOSTINGHTTP_QNAME = new QName("http://wsdl.bukopin.co.id/cbs/posting", "CBSPostingHTTP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:wsdl/CBSPostingHttp.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CBSPOSTINGHTTP_WSDL_LOCATION = url;
        CBSPOSTINGHTTP_EXCEPTION = e;
    }

    public CBSPostingHTTP() {
        super(__getWsdlLocation(), CBSPOSTINGHTTP_QNAME);
    }

    public CBSPostingHTTP(WebServiceFeature... features) {
        super(__getWsdlLocation(), CBSPOSTINGHTTP_QNAME, features);
    }

    public CBSPostingHTTP(URL wsdlLocation) {
        super(wsdlLocation, CBSPOSTINGHTTP_QNAME);
    }

    public CBSPostingHTTP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CBSPOSTINGHTTP_QNAME, features);
    }

    public CBSPostingHTTP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CBSPostingHTTP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PostingPT
     */
    @WebEndpoint(name = "PostingPTEndpoint0")
    public PostingPT getPostingPTEndpoint0() {
        return super.getPort(new QName("http://wsdl.bukopin.co.id/cbs/posting", "PostingPTEndpoint0"), PostingPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostingPT
     */
    @WebEndpoint(name = "PostingPTEndpoint0")
    public PostingPT getPostingPTEndpoint0(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsdl.bukopin.co.id/cbs/posting", "PostingPTEndpoint0"), PostingPT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CBSPOSTINGHTTP_EXCEPTION!= null) {
            throw CBSPOSTINGHTTP_EXCEPTION;
        }
        return CBSPOSTINGHTTP_WSDL_LOCATION;
    }

}
